export const refs = {
  letter: document.querySelector('.menu__link'),
  menu_wrap: document.querySelector('.menu'),
  menu_container: document.querySelector('.card__list'),
  page: document.querySelector('.page'),
  buttonChangeTheme: document.querySelector('.switcher__svg'),
  body: document.querySelector('body'),
  confirmButtonEl: document.querySelector('.modal__btn'),
  backdropEntranceEl: document.querySelector('.backdrop-entrance'),
  backdropEl: document.querySelector('.backdrop'),
  headerEl: document.querySelector('.header__container'),
  formEl: document.querySelector('.form_input'),
  readMoreEl: document.querySelector('.card__btn'),
  closeBtnEl: document.querySelector('.modal-close'),
  cardListEl: document.querySelector('ul.card__list'),
  modalInfoDivEl: document.querySelector('.modal-info'),
  modalCard: document.querySelector('.modal-content-wrap'),
  filmList: document.querySelector('.film-list'),
  heroImg: document.querySelector('.hero__img'),
  heroImgWrap: document.querySelector('.hero__img-wrap'),
  modalFilmWrap: document.querySelector('.modal-film-wrap'),
  queueModalBtnEl: document.querySelector('.modal-film-button'),
  watchedModalBtnEl: document.querySelector('#watched'),
  watchedHederBtnEl: document.querySelector('.watched-btn'),
  queueHederBtnEl: document.querySelector('.queue-btn'),
  // filmItemEl: document.querySelectorAll('.film-item'),
  paginationWrapEl: document.querySelector('.pagination__wrap'),
};
