export const refs = {
    letter: document.querySelector('.menu__link'),
    menu_wrap: document.querySelector('.menu'),
    menu_container: document.querySelector('.card__list'),
    page: document.querySelector('.page'),
    buttonChangeTheme: document.querySelector('.switcher__svg'),
    body: document.querySelector('body'),
    confirmButtonEl: document.querySelector('.modal__btn'),
    backdropEl: document.querySelector('.backdrop'),
    bodyEl: document.querySelector('.page'),
    headerEl: document.querySelector('.header__container'),
    formEl: document.querySelector('.form_input'),
    readMoreEl: document.querySelector('.card__btn'),
    closeBtnEl: document.querySelector('.modal-close'),
    cardListEl:document.querySelector('ul.card__list'),
    modalInfoDivEl: document.querySelector('.modal-info'),
};